#server
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
    
#DB    
spring:
# 마리아DB
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://146.56.99.53:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: mingu

# 오라클
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@138.2.112.96:1521/xe
      username: mingu
      password: mingu

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
# mybatis
mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    cache-enabled: false
    jdbc-type-for-null: null